version: 2

project_name: ghub-desk

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ghub-desk
    main: ./main.go
    binary: ghub-desk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X cmd.appVersion={{.Version}}
      - -X cmd.appCommit={{.Commit}}
      - -X cmd.appDate={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: takihito
    name: ghub-desk
  draft: false
  prerelease: auto

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"